# Generated by Django 3.2 on 2024-03-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_recipe_is_favorited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
    ]
